#pragma once

namespace tinyc::lexer {

enum class TokenType
{
    /* Single-character tokens */
    DOT, COMMA, SEMICOLON, COLON, LPAREN, RPAREN, LBRACE, RBRACE,
    LBRACKET, RBRACKET,
    PLUS, MINUS, STAR, SLASH, PERCENT, AMPERSAND, PIPE,
    CARET, BANG, TILDE, QUESTION, EQUAL, LESS, GREATER,

    /* Two-character tokens */
    PLUS_PLUS, MINUS_MINUS, EQUAL_EQUAL, BANG_EQUAL,
    LESS_EQUAL, GREATER_EQUAL, AMPERSAND_AMPERSAND, PIPE_PIPE,
    LEFT_SHIFT, RIGHT_SHIFT, PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL,
    SLASH_EQUAL, PERCENT_EQUAL, AMPERSAND_EQUAL, PIPE_EQUAL,
    CARET_EQUAL, LEFT_SHIFT_EQUAL, RIGHT_SHIFT_EQUAL,
    ARROW,

    /* Literals */
    IDENTIFIER, INT_LITERAL, UNSIGNED_LITERAL, STRING_LITERAL, TRUE, FALSE, NULLPTR,

    /* Keywords */
    IF, FOR, ELSE, WHILE, RETURN, BREAK, CONTINUE, DO,
    STRUCT, INT, CHAR, BOOL, UNSIGNED, PRINT, ASSERT,

    END_OF_FILE,
};
};